### ISSUE TITLE
🐛 [BUG] MySpools Page not showing pricing.

### ISSUE THREAD

**Issue by mikebronner** [MarksMakerSpace/filament-profiles#54] opened 2024-12-22 19:07 UTC
**Describe the bug**
I would love to see pricing on My Spools page, it is indicated in the listing table, but not being displayed.

Additionally, that would quickly let me see if the current price is reasonable. What would be even better would be to indicate if the price is lower than average for that specific filament, indicating it might be on sale and I could quickly stock up while the price is low.

Thanks!

**Comment by jklewa** [comment] 2024-12-23 04:49
I believe this is caused by a data serialization issue. Inspecting the RSC requests, the price_data is a string that contains the actual json object.

There are also "[object]" strings in some unexpected places. Those also show up on the main filaments page - so not strictly related to this issue.

**Comment by markcarroll** [comment] 2024-12-23 07:12
Thanks for the report. I dug in and realized that I had to convert a json column to text to build the summary table. converted it back client side so the price data is properly extracted now.  

@jklewa I've seen some of those [object] strings around too but can't work out how they got there. still trying to track that one down.  Closing this as the main issue is now solved.

**Closed by markcarroll** 2024-12-23 07:12 UTC
Labels: bug

**Comment by mikebronner** [comment] 2024-12-23 12:20
awesome, thank you for fixing this so quickly, I now see prices as expected. :)
